package org.ilerna.song_swipe_frontend.presentation.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006A6A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF00FFFF)
val onPrimaryContainerLight = Color(0xFF007272)
val secondaryLight = Color(0xFFA900A9)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF00FF)
val onSecondaryContainerLight = Color(0xFF510051)
val tertiaryLight = Color(0xFF9B0098)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBE23B9)
val onTertiaryContainerLight = Color(0xFFFFEEF8)
val errorLight = Color(0xFF815500)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFBD59)
val onErrorContainerLight = Color(0xFF744C00)
val backgroundLight = Color(0xFFF2FBFA)
val onBackgroundLight = Color(0xFF151D1D)
val surfaceLight = Color(0xFFF2FBFA)
val onSurfaceLight = Color(0xFF151D1D)
val surfaceVariantLight = Color(0xFFD5E6E5)
val onSurfaceVariantLight = Color(0xFF3A4A49)
val outlineLight = Color(0xFF6A7A7A)
val outlineVariantLight = Color(0xFFB9CAC9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF293232)
val inverseOnSurfaceLight = Color(0xFFEAF3F2)
val inversePrimaryLight = Color(0xFF00DDDD)
val surfaceDimLight = Color(0xFFD3DCDB)
val surfaceBrightLight = Color(0xFFF2FBFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFECF5F4)
val surfaceContainerLight = Color(0xFFE7F0EF)
val surfaceContainerHighLight = Color(0xFFE1EAE9)
val surfaceContainerHighestLight = Color(0xFFDBE4E3)


val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF003737)
val primaryContainerDark = Color(0xFF00FBFB)
val onPrimaryContainerDark = Color(0xFF007070)
val secondaryDark = Color(0xFFFFABF3)
val onSecondaryDark = Color(0xFF5B005B)
val secondaryContainerDark = Color(0xFFFF00FF)
val onSecondaryContainerDark = Color(0xFF510051)
val tertiaryDark = Color(0xFFFFABF1)
val onTertiaryDark = Color(0xFF5C005A)
val tertiaryContainerDark = Color(0xFFBE23B9)
val onTertiaryContainerDark = Color(0xFFFFEEF8)
val errorDark = Color(0xFFFFE0BA)
val onErrorDark = Color(0xFF442B00)
val errorContainerDark = Color(0xFFFFBD59)
val onErrorContainerDark = Color(0xFF744C00)
val backgroundDark = Color(0xFF0D1515)
val onBackgroundDark = Color(0xFFDBE4E3)
val surfaceDark = Color(0xFF0D1515)
val onSurfaceDark = Color(0xFFDBE4E3)
val surfaceVariantDark = Color(0xFF3A4A49)
val onSurfaceVariantDark = Color(0xFFB9CAC9)
val outlineDark = Color(0xFF839493)
val outlineVariantDark = Color(0xFF3A4A49)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDBE4E3)
val inverseOnSurfaceDark = Color(0xFF293232)
val inversePrimaryDark = Color(0xFF006A6A)
val surfaceDimDark = Color(0xFF0D1515)
val surfaceBrightDark = Color(0xFF323B3B)
val surfaceContainerLowestDark = Color(0xFF071010)
val surfaceContainerLowDark = Color(0xFF151D1D)
val surfaceContainerDark = Color(0xFF192121)
val surfaceContainerHighDark = Color(0xFF232C2B)
val surfaceContainerHighestDark = Color(0xFF2E3636)

// SongSwipe Brand Colors - Neon Gradient
val NeonOrange = Color(0xFFF69752)
val NeonPink = Color(0xFFF35987)
val NeonPurple = Color(0xFF736FE7)
val NeonCyan = Color(0xFF20CBD1)
val NeonGreen = Color(0xFF1DB954)  // Spotify green
val NeonRed = Color(0xFFFF5252)    // Dislike red

val NeonGradientColors = listOf(NeonOrange, NeonPink, NeonPurple, NeonCyan)

// Common alpha values for text
const val ContentAlphaHigh = 1.0f
const val ContentAlphaMedium = 0.7f
const val ContentAlphaDisabled = 0.6f
const val ContentAlphaLow = 0.5f